use_frameworks!

target 'RMSwiftSideController_Example' do
  pod 'RMSwiftSideController', :path => '../'

  target 'RMSwiftSideController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
